### ISSUE TITLE
PWM calculation

### ISSUE THREAD

**Issue by uncodead** [nagius/SmartThermostat#1]
Hello, why did you multiplicate the output with PWM PERIOD and then divide by 100?

 // Simulate low frequency PWM
  if((pid.output * PWM_PERIOD)/100 > now - pid.windowStartTime)
  {

**Comment by zenagius** [comment]
Hi,
This is a very good question, I should have put more comments.

If I recall correctly, `pid.output` is a percentage, that's why I divide it by 100 before converting it in time period (miliseconds).

Anyway, the PID algorithm is really hard to tune properly. I didn't get satisfying results without huge oscillations because of the inertia of my room. The simple hysteresis mode is more efficient.

**Comment by nagius** [comment]
Hi,
This is a very good question, I should have put more comments.

If I recall correctly, `pid.output` is a percentage, that's why I divide 
it by 100 before converting it in time period (miliseconds).

Anyway, the PID algorithm is really hard to tune properly. I didn't get 
satisfying results without huge oscillations because of the inertia of 
my room. The simple hysteresis mode is more efficient.
